domain: letsbuild.cloud
url: https://letsbuild.cloud
theme: minima
title: Let's Build
description: Cloud and software development content
minima:
  social_links:
    twitter: bracegirdle_me
    github: sbracegirdle
    linkedin: simon-bracegirdle